/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//plugin/': RouteRecordInfo<
      '//plugin/',
      '/plugin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/favorite-selection/': RouteRecordInfo<
      '//plugin/favorite-selection/',
      '/plugin/favorite-selection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/favorite-selection/hud': RouteRecordInfo<
      '//plugin/favorite-selection/hud',
      '/plugin/favorite-selection/hud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/island-toggle/': RouteRecordInfo<
      '//plugin/island-toggle/',
      '/plugin/island-toggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/island-toggle/done': RouteRecordInfo<
      '//plugin/island-toggle/done',
      '/plugin/island-toggle/done',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/island-toggle/idle': RouteRecordInfo<
      '//plugin/island-toggle/idle',
      '/plugin/island-toggle/idle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/island-toggle/running': RouteRecordInfo<
      '//plugin/island-toggle/running',
      '/plugin/island-toggle/running',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//plugin/settings/': RouteRecordInfo<
      '//plugin/settings/',
      '/plugin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/plugins/index.vue': {
      routes:
        | '//plugin/'
      views:
        | never
    }
    'src/plugins/favorite-selection/pages/index.vue': {
      routes:
        | '//plugin/favorite-selection/'
      views:
        | never
    }
    'src/plugins/favorite-selection/pages/hud.vue': {
      routes:
        | '//plugin/favorite-selection/hud'
      views:
        | never
    }
    'src/plugins/island-toggle/pages/index.vue': {
      routes:
        | '//plugin/island-toggle/'
      views:
        | never
    }
    'src/plugins/island-toggle/pages/done.vue': {
      routes:
        | '//plugin/island-toggle/done'
      views:
        | never
    }
    'src/plugins/island-toggle/pages/idle.vue': {
      routes:
        | '//plugin/island-toggle/idle'
      views:
        | never
    }
    'src/plugins/island-toggle/pages/running.vue': {
      routes:
        | '//plugin/island-toggle/running'
      views:
        | never
    }
    'src/plugins/settings/pages/index.vue': {
      routes:
        | '//plugin/settings/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
